services:
  db-auth:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: speakeasy
      POSTGRES_PASSWORD: speakeasy
      POSTGRES_DB: speakeasy_auth
    ports:
      - '5432:5432'
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  db-user:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: speakeasy
      POSTGRES_PASSWORD: speakeasy
      POSTGRES_DB: speakeasy_user
    ports:
      - '5433:5432'
    volumes:
      - pgdata-user:/var/lib/postgresql/data

volumes:
  pgdata-auth:
  pgdata-user:
